FROM node:20-alpine AS dev

WORKDIR /app

COPY package*.json ./
RUN apk add curl && \
    npm install && \
    npm cache clean --force

COPY . .

ENV PATH /app/node_modules/.bin:$PATH

EXPOSE 3000
CMD ["npm", "run", "dev"]
