flowchart TD
    A[User inputs Industry, Airport, Dates] --> B[Matching Events Shown]
    B --> C[User selects an Event]
    C --> D[Nearby Hotels are displayed max 9]
    D --> E[User selects a Hotel or clicks 'Show More']
    E --> F[Three Flight Options displayed]
    F --> G[User selects a Flight external link]
    G --> H[Event Info and Ticket Purchase Link]